<a href="https://colab.research.google.com/github/Javiour2003/Compute_Tasks/blob/main/Jatin_Jadhav_Bagging_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('/content/churndata_processed.csv')
df.head(10)

months  multiple    gb_mon  security  backup  protection  support  \
0    0.00         0  0.094118         0       0           1        0   
1    0.00         1  0.200000         0       1           0        0   
2    0.25         1  0.611765         0       0           0        0   
3    0.25         0  0.141176         0       1           1        0   
4    0.50         1  0.164706         0       0           0        0   
5    0.25         1  0.211765         0       0           1        0   
6    0.00         0  0.352941         0       0           0        0   
7    1.00         0  0.282353         0       1           1        0   
8    0.00         1  0.223529         0       0           0        0   
9    0.00         0  0.211765         1       0           0        0   

   unlimited  contract  paperless  ...  payment_Credit Card  \
0          0       0.0          1  ...                    0   
1          1       0.0          1  ...                    1   
2          1       0.0          1  ...                    0   
3          1       0.0          1  ...                    0   
4          1       0.0          1  ...                    0   
5          0       0.0          1  ...                    0   
6          1       0.0          1  ...                    0   
7          1       0.0          1  ...                    0   
8          1       0.0          1  ...                    0   
9          0       0.0          0  ...                    0   

   payment_Mailed Check  internet_type_DSL  internet_type_Fiber Optic  \
0                     0                  1                          0   
1                     0                  0                          1   
2                     0                  0                          1   
3                     0                  0                          1   
4                     0                  0                          1   
5                     0                  0                          1   
6                     1                  0                          1   
7                     0                  1                          0   
8                     1                  0                          1   
9                     0                  0                          1   

   internet_type_None  offer_Offer A  offer_Offer B  offer_Offer C  \
0                   0              0              0              0   
1                   0              0              0              0   
2                   0              0              0              0   
3                   0              0              0              1   
4                   0              0              0              1   
5                   0              0              0              1   
6                   0              0              0              0   
7                   0              0              1              0   
8                   0              0              0              0   
9                   0              0              0              0   

   offer_Offer D  offer_Offer E  
0              0              0  
1              0              1  
2              1              0  
3              0              0  
4              0              0  
5              0              0  
6              0              1  
7              0              0  
8              1              0  
9              0              1  

[10 rows x 23 columns]

In [3]:
df.shape

(7043, 23)

In [5]:
df.columns

Index(['months', 'multiple', 'gb_mon', 'security', 'backup', 'protection',
       'support', 'unlimited', 'contract', 'paperless', 'monthly',
       'satisfaction', 'churn_value', 'payment_Credit Card',
       'payment_Mailed Check', 'internet_type_DSL',
       'internet_type_Fiber Optic', 'internet_type_None', 'offer_Offer A',
       'offer_Offer B', 'offer_Offer C', 'offer_Offer D', 'offer_Offer E'],
      dtype='object')

In [5]:
df['churn_value'].value_counts()

0    5174
1    1869
Name: churn_value, dtype: int64

In [6]:

x=(df.drop('churn_value',axis=1)).iloc[:,:]
y=df.loc[:,'churn_value']
     

In [11]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
x_resampled, y_resampled = ros.fit_resample(x, y)
print(y_resampled.value_counts())

1    5174
0    5174
Name: churn_value, dtype: int64


In [12]:
x=x_resampled
y=y_resampled

In [14]:
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

kfold = model_selection.StratifiedKFold(n_splits = 3)
 
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
 
# no. of base classifier
num_trees = 500
 
# bagging classifier
model = BaggingClassifier(base_estimator = classifier,
                          n_estimators = num_trees,
                          random_state = 0)

results = model_selection.cross_val_score(model, x, y, cv = kfold)
print("accuracy :")
print(results.mean())

accuracy :
0.97187895952478


In [15]:
print(results)

[0.9684058  0.97158597 0.97564511]


In [25]:
l = x.iloc[1,:]
l=np.array(l)
l

array([0.        , 1.        , 0.2       , 0.        , 1.        ,
       0.        , 0.        , 1.        , 0.        , 1.        ,
       0.62089552, 0.5       , 1.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.        ])

In [23]:
model.fit(x,y)


BaggingClassifier(base_estimator=RandomForestClassifier(criterion='entropy',
                                                        n_estimators=10,
                                                        random_state=0),
                  n_estimators=500, random_state=0)

In [30]:
y= model.predict(l.reshape(1,-1))
y

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but BaggingClassifier was fitted with feature names
  warnings.warn(


array([1])

In [32]:
df['churn_value']

0       1
1       1
2       1
3       1
4       1
       ..
7038    0
7039    0
7040    0
7041    0
7042    0
Name: churn_value, Length: 7043, dtype: int64